version: '3'
services:
  frontend:
   container_name: frontend
   image: bchepngeno1/client
   build:
    context: ./client
    dockerfile: Dockerfile
   ports:
     - 3000:3000
   networks:
     frontend-tier-network:
       ipv4_address: 172.128.0.3
   depends_on:
     - backend

  backend:
   container_name: backend
   image: bchepngeno1/backend
   build:
    context: ./backend
    dockerfile: Dockerfile
   ports:
     - 5000:5000
   environment:
    PORT: 5000
    MONGO_URI: 'mongodb://brillian:lenovo@172.127.0.1:27017'
   depends_on:
     - mongo
   networks:
     backend-tier-network:
       ipv4_address: 172.127.0.2
     frontend-tier-network:
       ipv4_address: 172.128.0.2
  mongo:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: brillian
      MONGO_INITDB_ROOT_PASSWORD: lenovo
volumes:
  mongodb_data:
networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16