version: '3'
services:
  frontend:
   container_name: frontend
   build:
    context: ./client
    dockerfile: Dockerfile
   image: ms-frontend
   ports:
     - 3000:3000
   networks:
     frontend-tier-network:
       ipv4_address: 172.128.0.3
   depends_on:
     - backend

  backend:
   container_name: backend
   build:
    context: ./backend
    dockerfile: Dockerfile
   image: ms-backend
   ports:
     - "6000:6000"
   environment:
    PORT: 6000
    MONGO_URI: 'mongodb://brillian:lenovo@172.127.0.1:27017'
   depends_on:
     - mongo
   networks:
     backend-tier-network:
       ipv4_address: 172.127.0.2
     frontend-tier-network:
       ipv4_address: 172.128.0.2
  mongo:
    container_name: database
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: brillian
      MONGO_INITDB_ROOT_PASSWORD: lenovo
networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16